use_frameworks!

platform :ios, '9.0'

target 'SimpleExpandableView_Example' do
  pod 'SimpleExpandableView', :path => '../'

  target 'SimpleExpandableView_Tests' do
    inherit! :search_paths

    
  end
end
